repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key

  # isort
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.3
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [ "--profile", "black", "--filter-files" ]

  # black
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        args: # arguments to configure black
          - --line-length=100
          - --include='\.pyi?$'

          # these folders won't be formatted by black
          - --exclude="""\.git |
            \.__pycache__|
            \.hg|
            \.mypy_cache|
            \.venv|
            _build|
            buck-out|
            build|
            dist"""

        language_version: python3.10
