"""initial_migration

Revision ID: 510eafba3782
Revises:
Create Date: 2023-02-16 16:02:08.850563+00:00

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import func

# revision identifiers, used by Alembic.
revision = "510eafba3782"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'assets',
        sa.Column('asset_id', sa.String(50), primary_key=True),
        sa.Column('asset_name', sa.String(50)),
        sa.Column('asset_type', sa.String(50)),
        sa.Column('s3_location', sa.String(100)),
        sa.Column('changelist', sa.Integer),
        sa.Column('checksum', sa.String(50)),
        sa.Column('time_stamp', sa.DateTime(timezone=True), server_default=func.now(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assets')
    # ### end Alembic commands ###
