name: Test

on:
  push:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.10
      - name: Run Pre-Commit
        uses: pre-commit/action@v3.0.0
      - name: Create .env file
        uses: DamianReeves/write-file-action@master
        with:
          path: .env.ci
          contents: |
            ENV="test"
            CONSOLE_LOGGER=1
            FILE_LOGGER=0
            LOG_LEVEL=DEBUG
            PRIVATE_API_USERNAME=${{secrets.PRIVATE_API_USERNAME}}
            PRIVATE_API_PASSWORD=${{secrets.PRIVATE_API_PASSWORD}}
            PGSQL_READER_HOST=db
            PGSQL_WRITER_HOST=db
            PGSQL_PORT=5432
            PGSQL_PASS=${{secrets.PGSQL_PASS}}
            PGSQL_USER=postgres
            PGSQL_DB_NAME=postgres
            DYNAMO_ENDPOINT="http://dynamodb-local:8000"
            AWS_ACCESS_KEY_ID=localawskeys1
            AWS_SECRET_ACCESS_KEY=localawskeys2
            REDIS_POOL_SIZE=3
            REDIS_HOST=redis
            REDIS_PORT=6379
            S3_ENDPOINT="http://minio:9000"


          write-mode: append
      - name: docker-compose -f docker-compose-ci.yml up
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: docker-compose -f docker-compose-ci.yml up -d
      - name: Check running containers
        run: docker-compose -f docker-compose-ci.yml ps -a
      - name: Check logs
        run: docker-compose -f docker-compose-ci.yml logs app
      - name: Run Alembic
        run: docker-compose -f docker-compose-ci.yml exec -T app poetry run alembic upgrade head
      - name: Run pytest
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        uses: pavelzw/pytest-action@v2.1.1
        with:
          verbose: true
          custom-pytest: docker-compose -f docker-compose-ci.yml exec -T app poetry run pytest -vv
          emoji: true
          job-summary: true
          report-title: 'Test Report'
          click-to-expand: false
